version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    volumes: 
      - ./etc/loki/local-config.yaml:/etc/loki/local-config.yaml
    # external_links: 
    #   - grafana
      
  promtail:
    image: grafana/promtail:2.0.0
    volumes:
      - /var/log:/var/log
      - ./etc/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    volumes: 
      - ./grafana/:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/log:/var/log/grafana
    ports:
      - "3000:3000"
    networks:
      - loki





