version: "3.8"


services:

  promtail:
    image: grafana/promtail:2.0.0
    container_name: loki-promtail
    volumes:
      - ./config.yaml:/etc/promtail/config.yaml
      - ./positions.yaml:/tmp/positions.yaml
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/config.yaml
    restart: always
