version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.0.0
    restart: always
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    # network_mode: bridge
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:7.0.0
    container_name: kibana
    # network_mode: bridge
    ports: 
      - 5601:5601
    # volumes: 
    #   - ./data/kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elasticsearch

