server:
    http_listen_port: 9080
    grpc_listen_port: 0
    log_level: "debug"
  
positions:
    filename: /tmp/positions.yaml
  
clients:
    - url: http://139.155.5.58:80/loki/api/v1/push
  
scrape_configs:
  - job_name: coconut_api
    static_configs:
    - targets:
      - localhost
      labels:
        job: coconut_api
        env: test
        __path__: /data/coconut_api/log/*.log*