version: "3.8"

networks:
  loki:

services:

  # grafana:
  #   image: grafana/grafana:7.3.4
  #   container_name: loki-grafana
  #   ports:
  #     - "3000:3000"
  #   volumes: 
  #     - ./grafana/:/var/lib/grafana
  #     - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  #   networks:
  #     - loki
  #   restart: always

  # loki-gateway:
  #   image: nginx:1.19
  #   volumes:
  #     - ./config/nginx-loki-gateway.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80"
  #     - "3100"
  #   networks:
  #     - loki

  loki-frontend:
    image: grafana/loki:2.0.0
    # container_name: loki-frontend
    volumes:
      - ./config:/etc/loki/
    ports:
      - "32779-32780:3100"
    command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=query-frontend"
    networks:
      - loki
    deploy:
      mode: replicated
      replicas: 2
    restart: always

  loki:
    image: grafana/loki:2.0.0
    volumes:
      - ./config:/etc/loki/
      - ./loki:/loki
    ports:
      - "32781-32783:3100"
      - "32784-32786:7946"
    deploy:
      mode: replicated
      replicas: 3
    command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=all"
    networks:
      - loki
    restart: on-failure

  # loki-1:
  #   image: grafana/loki:2.0.0
  #   container_name: loki-1
  #   volumes:
  #     - ./config:/etc/loki/
  #     - ./loki:/loki
  #   ports:
  #     - "32781:3100"
  #     - "32782:7946"
  #   command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=all"
  #   networks:
  #     - loki
  #   restart: on-failure

  # loki-2:
  #   image: grafana/loki:2.0.0
  #   container_name: loki-2
  #   volumes:
  #     - ./config:/etc/loki/
  #     - ./loki:/loki
  #   ports:
  #     - "32783:3100"
  #     - "32784:7946"
  #   command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=all"
  #   networks:
  #     - loki
  #   restart: on-failure

  # loki-3:
  #   image: grafana/loki:2.0.0
  #   container_name: loki-3
  #   volumes:
  #     - ./config:/etc/loki/
  #     - ./loki:/loki
  #   ports:
  #     - "32785:3100"
  #     - "32786:7946"
  #   command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=all"
  #   networks:
  #     - loki
  #   restart: on-failure
