version: "3.3"

networks:
  loki:

services:
  # grafana:
  #   image: grafana/grafana:7.3.4
  #   volumes: 
  #    - ./grafana.ini:/etc/grafana/grafana.ini
  #   ports:
  #     - "3044:3000"
  #   networks:
  #     - loki

  loki-frontend:
    image: grafana/loki:2.0.0
    # container_name: loki-frontend
    volumes:
      - ./config:/etc/loki/
    ports:
      - "32779-32780:3100"
    command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=query-frontend"
    networks:
      - loki
    deploy:
      mode: replicated
      replicas: 2
    restart: always

  loki-1:
    image: grafana/loki:2.0.0
    volumes:
      - ./config:/etc/loki/
      - ./loki:/loki
    ports:
      - "32781:3100"
      - "32782:7946"
    command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=all"
    networks:
      - loki
    restart: on-failure

  loki-2:
    image: grafana/loki:2.0.0
    volumes:
      - ./config:/etc/loki/
      - ./loki:/loki
    ports:
      - "32783:3100"
      - "32784:7946"
    command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=all"
    networks:
      - loki
    restart: on-failure

  loki-3:
    image: grafana/loki:2.0.0
    volumes:
      - ./config:/etc/loki/
      - ./loki:/loki
    ports:
      - "32785:3100"
      - "32786:7946"
    command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=all"
    networks:
      - loki
    restart: on-failure