version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.0.0
    restart: always
    container_name: log-stack-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    volumes: 
      - ./config/loki/local-config.yaml:/etc/loki/local-config.yaml -print-config-stderr=true
      - ./loki:/loki
      
  promtail:
    image: grafana/promtail:2.0.0
    restart: always
    container_name: log-stack-promtail
    volumes:
      - /var/log:/var/log
      - ./config/promtail/config.yml:/etc/promtail/config.yml
      - ./promtail/positions.yaml:/tmp/positions.yaml
    command: -config.file=/etc/promtail/config.yml -print-config-stderr=true
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    restart: always
    container_name: log-stack-grafana
    volumes: 
      - ./grafana/:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/log:/var/log/grafana
    ports:
      - "3000:3000"
    networks:
      - loki





